### ISSUE TITLE
package not found in gopkgs.com

### ISSUE THREAD

**Issue by danielmt** [rainycape/memcache#1]
$ go get gopkgs.com/memcache.v2
# cd .; git clone http://gopkgs.com/memcache.v2 /Users/daniel/go/src/gopkgs.com/memcache.v2
Cloning into '/Users/daniel/go/src/gopkgs.com/memcache.v2'...
fatal: repository 'http://gopkgs.com/memcache.v2/' not found
package gopkgs.com/memcache.v2: exit status 128

**Comment by rainycape** [comment]
Thanks for the heads up. It was an issue with the gopkgs.com server. It's fixed now.

**Comment by robbiet480** [comment]
@rainycape Seems that it's down again. I can't `go get gopkgs.com/memcache.v1/` and when I go to http://gopkgs.com/memcache.v1/ I get a 404 and a message saying `driver: bad connection`. Can this package just be hosted on GitHub? I've tried installing it manually from GitHub but it seems you have added a [poison pill](https://github.com/rainycape/memcache/blob/1f2ac2738f0d4fc75f2985b68e7b2e17376e104f/gopkgs.go#L20-L23) so that it can only be installed from gopkgs.com. Commenting out the poison pill fixes the issue.

**Comment by robbiet480** [comment]
I've found that if I run a command like `git clone -b v1 git@github.com:rainycape/memcache.git $GOPATH/src/gopkgs.com/memcache.v1` to clone directly from GitHub everything works (because the poison pill doesn't run, since it thinks that it's installed in the correct directory)

**Comment by rainycape** [comment]
@robbiet480 I'm updating the package in the next minutes to stop forcing the import path from gopkgs.com. The reason for doing so is that someone has been DDoS'ing gopkgs.com for several weeks and I'm just sick of it, so I'm shutting it down. Please, import directly from Github from now on.

**Comment by robbiet480** [comment]
@rainycape Thanks! Would you mind also updating the v1 branch? Actually, v1 may need to be split into it's own repo since you can't grab branches in `import` statements.

**Comment by rainycape** [comment]
@robbiet480 I don't really see the point of maintaining the v1 branch. The only breaking change in the master branch is minimal (New() might return an error) and it's actually correct. In v1 New() will silently accept an invalid host or server.
